name: smart_cap  # Change this to your project's name
description: A new Flutter project.

publish_to: 'none'  # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"  # Ensure this matches your Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  fl_chart: ^0.69.0  # Ensure this is a compatible version
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  syncfusion_flutter_gauges: ^20.3.47


# You may also want to include other dependencies your app uses

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: "assets/icon/app_icon.png"  # Change this path to your icon's path
  adaptive_icon_background: "#ffffff"  # Change this to your icon's background color
  adaptive_icon_foreground: "assets/icon/app_icon.png"  # Change this path to your icon's path
